spring:
  application:
    name: franquicias-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin@localhost:27017/franquiciasdb?authSource=admin}

server:
  port: ${SERVER_PORT:8080}
